# cloudbuild template
# https://cloud.google.com/cloud-build/docs/build-config

steps:
  # build audit-service
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "australia-southeast1-docker.pkg.dev/loyal-gateway-387301/notes/audit",
        ".",
        "-f",
        "service.dockerfile",
      ]
    dir: "./audit-service"
  # build auth-service
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "australia-southeast1-docker.pkg.dev/loyal-gateway-387301/notes/auth",
        ".",
        "-f",
        "service.dockerfile",
      ]
    dir: "./auth-service"
  # build bff-service
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "australia-southeast1-docker.pkg.dev/loyal-gateway-387301/notes/bff",
        ".",
        "-f",
        "service.dockerfile",
      ]
    dir: "./bff-service"
  # build notes-service
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "australia-southeast1-docker.pkg.dev/loyal-gateway-387301/notes/notes",
        ".",
        "-f",
        "service.dockerfile",
      ]
    dir: "./notes-service"
  # build ui-service
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "australia-southeast1-docker.pkg.dev/loyal-gateway-387301/notes/ui",
        ".",
        "-f",
        "service.dockerfile",
      ]
    dir: "./ui-service"
  # pull mongo image and push to gcr
  - name: "gcr.io/cloud-builders/docker"
    args: ["pull", "mongo"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "tag",
        "mongo",
        "australia-southeast1-docker.pkg.dev/loyal-gateway-387301/notes/mongo:latest",
      ]

images:
  - "australia-southeast1-docker.pkg.dev/loyal-gateway-387301/notes/notes"
  - "australia-southeast1-docker.pkg.dev/loyal-gateway-387301/notes/auth"
  - "australia-southeast1-docker.pkg.dev/loyal-gateway-387301/notes/bff"
  - "australia-southeast1-docker.pkg.dev/loyal-gateway-387301/notes/audit"
  - "australia-southeast1-docker.pkg.dev/loyal-gateway-387301/notes/ui"
  - "australia-southeast1-docker.pkg.dev/loyal-gateway-387301/notes/mongo"
