# cloudbuild template
# https://cloud.google.com/cloud-build/docs/build-config

steps:
  # ------------------------------------
  # Build Staget
  # ------------------------------------

  # build audit-service
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "australia-southeast1-docker.pkg.dev/$PROJECT_ID/notes/audit:$BUILD_ID",
        ".",
        "-f",
        "service.dockerfile",
      ]
    dir: "./audit-service"
  # build auth-service
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "australia-southeast1-docker.pkg.dev/$PROJECT_ID/notes/auth:$BUILD_ID",
        ".",
        "-f",
        "service.dockerfile",
      ]
    dir: "./auth-service"
  # build bff-service
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "australia-southeast1-docker.pkg.dev/$PROJECT_ID/notes/bff:$BUILD_ID",
        ".",
        "-f",
        "service.dockerfile",
      ]
    dir: "./bff-service"
  # build notes-service
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "australia-southeast1-docker.pkg.dev/$PROJECT_ID/notes/notes:$BUILD_ID",
        ".",
        "-f",
        "service.dockerfile",
      ]
    dir: "./notes-service"
  # build ui-service
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "australia-southeast1-docker.pkg.dev/$PROJECT_ID/notes/ui:$BUILD_ID",
        ".",
        "-f",
        "service.dockerfile",
      ]
    dir: "./ui-service"

  # ------------------------------------
  # Push Stage
  # ------------------------------------
  #   - "australia-southeast1-docker.pkg.dev/$PROJECT_ID/notes/notes"
  #   - "australia-southeast1-docker.pkg.dev/$PROJECT_ID/notes/auth"
  #   - "australia-southeast1-docker.pkg.dev/$PROJECT_ID/notes/bff"
  #   - "australia-southeast1-docker.pkg.dev/$PROJECT_ID/notes/audit"
  #   - "australia-southeast1-docker.pkg.dev/$PROJECT_ID/notes/ui"

  - name: "gcr.io/cloud-builders/docker"
    args: ["pull", "mongo:latest"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "tag",
        "mongo:latest",
        "australia-southeast1-docker.pkg.dev/$PROJECT_ID/notes/mongo:latest",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "australia-southeast1-docker.pkg.dev/$PROJECT_ID/notes/mongo:latest",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "australia-southeast1-docker.pkg.dev/$PROJECT_ID/notes/notes:$BUILD_ID",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "australia-southeast1-docker.pkg.dev/$PROJECT_ID/notes/auth:$BUILD_ID",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "australia-southeast1-docker.pkg.dev/$PROJECT_ID/notes/bff:$BUILD_ID",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "australia-southeast1-docker.pkg.dev/$PROJECT_ID/notes/audit:$BUILD_ID",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "australia-southeast1-docker.pkg.dev/$PROJECT_ID/notes/ui:$BUILD_ID",
      ]

  # ------------------------------------
  # apply deployment and service config
  # ------------------------------------
  - name: "gcr.io/cloud-builders/kubectl"
    args: ["apply", "-f", "deployment.yaml"]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=australia-southeast1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=notes-project-cluster"
      - "IMAGE_TAG=$BUILD_ID"

  - name: "gcr.io/cloud-builders/kubectl"
    args: ["apply", "-f", "service.yaml"]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=australia-southeast1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=notes-project-cluster"
      - "IMAGE_TAG=$BUILD_ID"

  # ------------------------------------
  # update images
  # ------------------------------------
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "set",
        "image",
        "deployment/notes-deployment",
        "notes=australia-southeast1-docker.pkg.dev/$PROJECT_ID/notes/notes:$BUILD_ID",
      ]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=australia-southeast1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=notes-project-cluster"
      - "IMAGE_TAG=$BUILD_ID"

  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "set",
        "image",
        "deployment/auth-deployment",
        "auth=australia-southeast1-docker.pkg.dev/$PROJECT_ID/notes/auth:$BUILD_ID",
      ]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=australia-southeast1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=notes-project-cluster"
      - "IMAGE_TAG=$BUILD_ID"

  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "set",
        "image",
        "deployment/bff-deployment",
        "bff=australia-southeast1-docker.pkg.dev/$PROJECT_ID/notes/bff:$BUILD_ID",
      ]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=australia-southeast1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=notes-project-cluster"
      - "IMAGE_TAG=$BUILD_ID"

  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "set",
        "image",
        "deployment/audit-deployment",
        "audit=australia-southeast1-docker.pkg.dev/$PROJECT_ID/notes/audit:$BUILD_ID",
      ]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=australia-southeast1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=notes-project-cluster"
      - "IMAGE_TAG=$BUILD_ID"

  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "set",
        "image",
        "deployment/ui-deployment",
        "ui=australia-southeast1-docker.pkg.dev/$PROJECT_ID/notes/ui:$BUILD_ID",
      ]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=australia-southeast1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=notes-project-cluster"
      - "IMAGE_TAG=$BUILD_ID"

options:
  logging: CLOUD_LOGGING_ONLY
