# cloudbuild template
# https://cloud.google.com/cloud-build/docs/build-config

steps:
  # build audit-service
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/loyal-gateway-387301/audit-service",
        ".",
        "-f",
        "service.dockerfile",
      ]
    dir: "./audit-service"
  # build auth-service
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/loyal-gateway-387301/auth-service",
        ".",
        "-f",
        "service.dockerfile",
      ]
    dir: "./auth-service"
  # build bff-service
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/loyal-gateway-387301/bff-service",
        ".",
        "-f",
        "service.dockerfile",
      ]
    dir: "./bff-service"
  # build notes-service
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/loyal-gateway-387301/notes-service",
        ".",
        "-f",
        "service.dockerfile",
      ]
    dir: "./notes-service"

images:
  # push audit-service artifact registry
  - "australia-southeast1-docker.pkg.dev/loyal-gateway-387301/audit"
  # push auth-service artifact registry
  - "australia-southeast1-docker.pkg.dev/loyal-gateway-387301/auth"
  # push bff-service artifact registry
  - "australia-southeast1-docker.pkg.dev/loyal-gateway-387301/bff"
  # push notes-service artifact registry
  - "australia-southeast1-docker.pkg.dev/loyal-gateway-387301/notes"
