apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: "australia-southeast1-docker.pkg.dev/tempo-387808/notes/ui:latest"
          ports:
            - containerPort: 3000
          env:
            - name: BFF_SERVICE_URI
              value: http://bff:80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: bff
          image: australia-southeast1-docker.pkg.dev/tempo-387808/notes/bff:latest
          ports:
            - containerPort: 3000
            # defining environment variables
          env:
            - name: AUDIT_SERVICE_URI
              value: http://audit:80
            - name: AUTH_SERVICE_URI
              value: http://auth:80
            - name: NOTES_SERVICE_URI
              value: http://notes:80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit
  template:
    metadata:
      labels:
        app: audit
    spec:
      containers:
        - name: audit
          image: australia-southeast1-docker.pkg.dev/tempo-387808/notes/audit:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_SERVICE_HOST
              value: localhost
            - name: IMAGE_TAG
              value: $(IMAGE_TAG)
        - name: audit-db
          image: australia-southeast1-docker.pkg.dev/tempo-387808/notes/mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: audit-db-volume
              mountPath: /data/db/audit
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
      volumes:
        - name: audit-db-volume
          persistentVolumeClaim:
            claimName: mongo-pv-claim-v2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: australia-southeast1-docker.pkg.dev/tempo-387808/notes/auth:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_SERVICE_HOST
              value: localhost
            - name: IMAGE_TAG
              value: $(IMAGE_TAG)
        - name: auth-db
          image: australia-southeast1-docker.pkg.dev/tempo-387808/notes/mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: auth-db-volume
              mountPath: /data/db/auth
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
      volumes:
        - name: auth-db-volume
          persistentVolumeClaim:
            claimName: mongo-pv-claim-v2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes
  template:
    metadata:
      labels:
        app: notes
    spec:
      containers:
        - name: notes
          image: australia-southeast1-docker.pkg.dev/tempo-387808/notes/notes:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_SERVICE_HOST
              value: localhost
            - name: IMAGE_TAG
              value: $(IMAGE_TAG)
        - name: notes-db
          image: australia-southeast1-docker.pkg.dev/tempo-387808/notes/mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: notes-db-volume
              mountPath: /data/db/notes
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
      volumes:
        - name: notes-db-volume
          persistentVolumeClaim:
            claimName: mongo-pv-claim-v2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-volume-v2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/home/dathalage/mongo-pv"
  claimRef:
    namespace: default
    name: mongo-pv-claim-v2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim-v2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
  MONGO_INITDB_ROOT_PASSWORD: ZXhhbXBsZQ==
---

