apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: "australia-southeast1-docker.pkg.dev/loyal-gateway-387301/notes/ui:latest"
          ports:
            - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: bff
          image: australia-southeast1-docker.pkg.dev/loyal-gateway-387301/notes/bff:latest
          ports:
            - containerPort: 3000
            # defining environment variables
          env:
            - name: AUDIT_SERVICE_URI
              value: http://audit:80
            - name: AUTH_SERVICE_URI
              value: http://auth:80
            - name: NOTES_SERVICE_URI
              value: http://notes:80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit
  template:
    metadata:
      labels:
        app: audit
    spec:
      containers:
        - name: audit
          image: australia-southeast1-docker.pkg.dev/loyal-gateway-387301/notes/audit:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example
            - name: MONGO_SERVICE_HOST
              value: localhost
            - name: IMAGE_TAG
              value: $(IMAGE_TAG)
        - name: audit-db
          image: australia-southeast1-docker.pkg.dev/loyal-gateway-387301/notes/mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: audit-db-volume
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example
      volumes:
        - name: audit-db-volume
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: australia-southeast1-docker.pkg.dev/loyal-gateway-387301/notes/auth:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example
            - name: MONGO_SERVICE_HOST
              value: localhost
            - name: IMAGE_TAG
              value: $(IMAGE_TAG)
        - name: auth-db
          image: australia-southeast1-docker.pkg.dev/loyal-gateway-387301/notes/mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: auth-db-volume
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example
      volumes:
        - name: auth-db-volume
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes
  template:
    metadata:
      labels:
        app: notes
    spec:
      containers:
        - name: notes
          image: australia-southeast1-docker.pkg.dev/loyal-gateway-387301/notes/notes:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example
            - name: MONGO_SERVICE_HOST
              value: localhost
            - name: IMAGE_TAG
              value: $(IMAGE_TAG)
        - name: notes-db
          image: australia-southeast1-docker.pkg.dev/loyal-gateway-387301/notes/mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: notes-db-volume
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example
      volumes:
        - name: notes-db-volume
          emptyDir: {}
