# simple docker compose file

version: '3.9'
services:
  # -------------------------------------
  # bff service
  # -------------------------------------
  bff:
    image: bff-service
    build:
      context: ./bff-service
      dockerfile: service.dockerfile
    ports:
      - "80:3000"
    restart: always

  # -------------------------------------
  # notes service
  # -------------------------------------
  notes:
    image: notes-service
    build:
      context: ./notes-service
      dockerfile: service.dockerfile
    ports:
      - "81:3000"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_SERVICE_HOST=notes-db
  notes-db:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./notes-service/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: always

  # -------------------------------------
  # auth service
  # -------------------------------------
  auth:
    image: auth-service
    build:
      context: ./auth-service
      dockerfile: service.dockerfile
    ports:
      - "82:3000"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_SERVICE_HOST=auth-db
  auth-db:
    image: mongo
    ports:
      - "27019:27017"
    volumes:
      - ./auth-service/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: always

  # -------------------------------------
  # audit service
  # -------------------------------------
  audit:
    image: audit-service
    build:
      context: ./audit-service
      dockerfile: service.dockerfile
    ports:
      - "83:3000"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_SERVICE_HOST: audit-db
  audit-db:
    image: mongo
    ports:
      - "27020:27017"
    volumes:
      - ./audit-service/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: always
  # -------------------------------------
  # ui service
  # -------------------------------------
  ui:
    image: ui-service
    build:
      context: ./ui-service
      dockerfile: service.dockerfile
    ports:
      - "84:3000"
    restart: always
