# simple docker compose file

version: '3.9'
services:
  # -------------------------------------
  # bff service
  # -------------------------------------
  bff:
    image: bff-service
    build:
      context: ./bff-service
      dockerfile: service.dockerfile
    environment:
      - AUTH_SERVICE_URI=http://auth:3000
      - NOTES_SERVICE_URI=http://notes:3000
      - AUDIT_SERVICE_URI=http://audit:3000
    ports:
      - "80:3000"
    restart: always
    networks:
      - custom
    depends_on:
      - auth

  # -------------------------------------
  # notes service
  # -------------------------------------
  notes:
    image: notes-service
    build:
      context: ./notes-service
      dockerfile: service.dockerfile
    ports:
      - "81:3000"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_SERVICE_HOST=notes-db
    depends_on:
      - notes-db
    networks:
      - custom
  notes-db:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./notes-service/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: always
    networks:
      - custom

  # -------------------------------------
  # auth service
  # -------------------------------------
  auth:
    image: auth-service
    build:
      context: ./auth-service
      dockerfile: service.dockerfile
    ports:
      - "82:3000"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_SERVICE_HOST=auth-db
    depends_on:
      - auth-db
    networks:
      - custom
  auth-db:
    image: mongo
    ports:
      - "27019:27017"
    volumes:
      - ./auth-service/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: always
    networks:
      - custom
  # -------------------------------------
  # audit service
  # -------------------------------------
  audit:
    image: audit-service
    build:
      context: ./audit-service
      dockerfile: service.dockerfile
    ports:
      - "83:3000"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_SERVICE_HOST: audit-db
    depends_on:
      - audit-db
    networks:
      - custom
  audit-db:
    image: mongo
    ports:
      - "27020:27017"
    volumes:
      - ./audit-service/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: always
    networks:
      - custom
  # -------------------------------------
  # ui service
  # -------------------------------------
  ui:
    image: ui-service
    build:
      context: ./ui-service
      dockerfile: service.dockerfile
    ports:
      - "84:3000"
    restart: always
    networks:
      - custom
    environment:
      - BFF_SERVICE_URL=http://bff:3000

networks:
  custom:
    driver: bridge
