apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  selector:
    app: ui
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: bff
spec:
  selector:
    app: bff
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: LoadBalancer
  env:
    - name: AUDIT_SERVICE_URI
      value: "http://audit:3000"
    - name: AUTH_SERVICE_URI
      value: "http://auth:3000"
    - name: NOTES_SERVICE_URI
      value: "http://notes:3000"
---
apiVersion: v1
kind: Service
metadata:
  name: audit
spec:
  selector:
    app: audit
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: notes
spec:
  selector:
    app: notes
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
